##Experiment 8
###Tools for EDA study of Numpy lib
### Name - arjit ujjawal
### Prn - 25070123142

In [2]:
#declartion of numpy
import numpy as np
a=np.array([10,30,56])
b=np.array([[1,3,4],[5,7,8]])
print (a)
print (b)


[10 30 56]
[[1 3 4]
 [5 7 8]]


In [5]:
#dimension of array
print(a.ndim)
print(b.ndim)

1
2


In [7]:
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [8]:
print(a.dtype)
print(b.dtype)

int64
int64


In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [19]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
c=a*2
d=a+5
print(c)
print(d)

[ 20  60 112]
[15 35 61]


In [23]:
np.mean(a)

np.float64(32.0)

In [26]:
print(np.median(a))
print(np.median(b))

30.0
4.5


In [27]:
np.max(a)

np.int64(56)

In [28]:
np.min(a)

np.int64(10)

In [29]:
np.sum(10)

np.int64(10)